import { ArrowRight, Minus, Plus, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useCart } from '../context/CartContext.jsx';

const money = v => `$${Number(v).toFixed(2)}`;

export default function Cart() {
  const { items, updateQuantity, removeItem, subtotal, shipping, tax, total } = useCart();
  return <main className="section"><div className="container"><div className="eyebrow">YOUR BAG</div><h1 className="page-title">Ready when you are.</h1>{!items.length ? <div className="empty-state large-empty"><h3>Your bag is waiting</h3><p>Explore the collection and add something worth keeping.</p><Link className="btn btn-dark" to="/shop">Continue shopping <ArrowRight size={17}/></Link></div> : <div className="cart-layout"><section className="cart-items">{items.map(item => <article className="cart-item" key={item.id}><Link to={`/product/${item.slug}`}><img src={item.imageUrl} alt={item.name}/></Link><div className="cart-item-info"><span className="eyebrow">{item.category}</span><Link to={`/product/${item.slug}`} className="cart-item-name">{item.name}</Link><span className="cart-item-price">{money(item.price)}</span><div className="cart-controls"><div className="qty-control"><button onClick={() => updateQuantity(item.id, item.quantity - 1)}><Minus size={15}/></button><span>{item.quantity}</span><button onClick={() => updateQuantity(item.id, item.quantity + 1)}><Plus size={15}/></button></div><button className="text-action" onClick={() => removeItem(item.id)}><Trash2 size={16}/> Remove</button></div></div><strong>{money(item.price * item.quantity)}</strong></article>)}</section><aside className="summary-card"><div className="eyebrow">ORDER SUMMARY</div><div className="summary-row"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div className="summary-row"><span>Shipping</span><strong>{shipping === 0 ? 'Free' : money(shipping)}</strong></div><div className="summary-row"><span>Estimated tax</span><strong>{money(tax)}</strong></div><div className="summary-divider"/><div className="summary-row total-row"><span>Total</span><strong>{money(total)}</strong></div><Link className="btn btn-dark full-btn" to="/checkout">Checkout <ArrowRight size={17}/></Link><p className="summary-note">Free shipping automatically applies to qualifying orders.</p></aside></div>}</div></main>;
}
