import { ArrowLeft, CheckCircle2 } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import api, { getErrorMessage } from '../services/api.js';
import { useCart } from '../context/CartContext.jsx';
import { useAuth } from '../context/AuthContext.jsx';

const money = v => `$${Number(v).toFixed(2)}`;

export default function Checkout() {
  const { items, subtotal, shipping, tax, total, clearCart } = useCart(); const { user } = useAuth(); const nav = useNavigate();
  const [form, setForm] = useState({ fullName:user?.name || '', line1:'', city:'', state:'', postalCode:'', country:'India', phone:'' });
  const [paymentMethod, setPaymentMethod] = useState('COD'); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [success,setSuccess]=useState(null);
  if (!items.length && !success) return <main className="section"><div className="container"><div className="empty-state"><h3>Your bag is empty</h3><Link className="btn btn-dark" to="/shop">Back to shop</Link></div></div></main>;
  if (success) return <main className="success-page"><div className="success-card"><CheckCircle2 size={54}/><div className="eyebrow">ORDER CONFIRMED</div><h1>Thank you, {user?.name?.split(' ')[0] || 'there'}.</h1><p>Your demo order <strong>{success.orderNumber}</strong> has been placed. You can track its status from your account.</p><div className="hero-actions center-actions"><Link className="btn btn-dark" to="/orders">View my orders</Link><Link className="text-link" to="/shop">Continue shopping</Link></div></div></main>;
  const submit = async e => { e.preventDefault(); setLoading(true); setError(''); try { const {data}=await api.post('/orders',{items:items.map(i=>({productId:i.id,quantity:i.quantity})),shippingAddress:form,paymentMethod}); clearCart(); setSuccess(data.order); } catch(err) { setError(getErrorMessage(err)); } finally { setLoading(false); } };
  return <main className="section"><div className="container"><Link className="back-link" to="/cart"><ArrowLeft size={17}/> Back to bag</Link><div className="checkout-layout"><form className="checkout-form" onSubmit={submit}><div className="checkout-head"><div><div className="eyebrow">CHECKOUT</div><h1>Let's get this moving.</h1><p>Enter delivery details. Payment methods here are demo-safe for the internship project.</p></div></div>{error && <div className="alert">{error}</div>}<section className="form-section"><h2>Delivery details</h2><div className="form-grid"><label>Full name<input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label>Phone<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="full-span">Address<input required value={form.line1} onChange={e=>setForm({...form,line1:e.target.value})} placeholder="Street, apartment, landmark"/></label><label>City<input required value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>State<input required value={form.state} onChange={e=>setForm({...form,state:e.target.value})}/></label><label>Postal code<input required value={form.postalCode} onChange={e=>setForm({...form,postalCode:e.target.value})}/></label><label>Country<input required value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></label></div></section><section className="form-section"><h2>Payment</h2><div className="payment-options">{[['COD','Cash on delivery','Pay when your order arrives.'],['UPI_DEMO','UPI (demo)','Demo flow — no real payment is processed.'],['CARD_DEMO','Card (demo)','Demo flow — no card data is stored.']].map(([value,label,desc])=><label className={`payment-option ${paymentMethod===value?'selected':''}`} key={value}><input type="radio" name="payment" value={value} checked={paymentMethod===value} onChange={()=>setPaymentMethod(value)}/><span><strong>{label}</strong><small>{desc}</small></span></label>)}</div></section><button className="btn btn-dark full-btn" disabled={loading}>{loading ? 'Placing order...' : `Place order · ${money(total)}`}</button></form><aside className="summary-card sticky-summary"><div className="eyebrow">YOUR ORDER</div>{items.map(i=><div className="mini-line" key={i.id}><span>{i.name} <small>× {i.quantity}</small></span><strong>{money(i.price*i.quantity)}</strong></div>)}<div className="summary-divider"/><div className="summary-row"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div className="summary-row"><span>Shipping</span><strong>{shipping===0?'Free':money(shipping)}</strong></div><div className="summary-row"><span>Tax</span><strong>{money(tax)}</strong></div><div className="summary-row total-row"><span>Total</span><strong>{money(total)}</strong></div></aside></div></div></main>;
}
